<a href="https://colab.research.google.com/github/rumorale/Capstone/blob/master/Ayudant%C3%ADas/A1/A1_02_listas_y_dataframes_desarrollo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ayudantía 1**

**Ayudante:** Rodrigo Morales Méndez<br>
**E-mail ayudante:** rumorale1@gmail.com



# **2 Listas y Dataframes**

## **2.1 Listas**

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando el **operador [ ]** (retorna lista), o bien usando **[ [ ] ]** (retorna el objeto) - "squarebrackets". 

    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [1]:
# 2. Listas y dataframes ------------
# 2.1 Listas  
lista1 <-list()

In [2]:
# estructura
str(lista1)

List of 5
 $ num   : num 6
 $ letra : chr "A"
 $ vector: num [1:3] 10 20 30
 $ matriz: num [1:4, 1:4] 8 0 0 0 0 8 0 0 0 0 ...
 $ lista :List of 2
  ..$ a: chr "hola"
  ..$ b: num 18


In [3]:
# Obtenemos la clase del objeto
class(lista1)

[1] "list"

In [6]:
# para saber el largo de la lista/vector
length(lista1)


[1] 5

NULL

In [7]:
# Para obtener los nombres de la lista
names(lista1)

[1] "num"    "letra"  "vector" "matriz" "lista"

In [8]:
# Ejemplo de una lista simple sin nombres
lista_test <- list("Hola",42,TRUE)
lista_test

names(lista_test)

[[1]]
[1] "Hola"

[[2]]
[1] 42

[[3]]
[1] TRUE

NULL

In [15]:
# Podemos combinar listas
lista2 <- list(
  primos = c(2,3,5,7),
  amigos = c(220,284)
)

list_comb <- list(lista1, lista2)
list_comb
names(list_comb) <- c("L1","L2")
list_comb
names(list_comb)

list_comb$L1$matriz

[[1]]
[[1]]$num
[1] 6

[[1]]$letra
[1] "A"

[[1]]$vector
[1] 10 20 30

[[1]]$matriz
     [,1] [,2] [,3] [,4]
[1,]    8    0    0    0
[2,]    0    8    0    0
[3,]    0    0    8    0
[4,]    0    0    0    8

[[1]]$lista
[[1]]$lista$a
[1] "hola"

[[1]]$lista$b
[1] 18



[[2]]
[[2]]$primos
[1] 2 3 5 7

[[2]]$amigos
[1] 220 284

$L1
$L1$num
[1] 6

$L1$letra
[1] "A"

$L1$vector
[1] 10 20 30

$L1$matriz
     [,1] [,2] [,3] [,4]
[1,]    8    0    0    0
[2,]    0    8    0    0
[3,]    0    0    8    0
[4,]    0    0    0    8

$L1$lista
$L1$lista$a
[1] "hola"

$L1$lista$b
[1] 18



$L2
$L2$primos
[1] 2 3 5 7

$L2$amigos
[1] 220 284

[1] "L1" "L2"

[,1] [,2] [,3] [,4]
[1,] 8    0    0    0   
[2,] 0    8    0    0   
[3,] 0    0    8    0   
[4,] 0    0    0    8

### **Acceso a los elementos de una lista**

Al igual que un vector, una lista es un arreglo unidimensional, por lo que es esperable que herede la misma forma de acceso.

#### **Acceso mediante posición**

En R, para acceder al "slot" de una lista, podemos utilizar `[]` indicando la posición a la que queremos acceder. Notar que en R distingue el uso de `[]` y `[[]]`. Para ilustrar este comportamiento, consideremosla lista "lista3", donde se observa que `lista3[2]` retorna una lista, mientras que `lista3[[2]]` retorna el character "A"








In [ ]:
str(lista3)

In [ ]:
# Acceso mediante posición. NOTA: Diferenciar entre eacceso con [] y con [[]]


In [ ]:
# Podemos combinar lo que hemos aprendido, por ejemplo, en el 4to slot hay una matriz y queremos obtener la 3ra fila #:= 0 0 8 0


#### **Acceso mediante nombre**

Cuando una lista posee nombres, podemos acceder a sus elementos referenciando su nombre, distinguiendo, al igual que por posición, el uso de `[]` y `[[]]`


In [ ]:
# Acceso mediante nombre. NOTA: Diferenciar entre eacceso con [] y con [[]]

#### **Acceso mediante "$"**

Finalmente, una de las opciones más simples para acceder a los elementos de una lista cuando sus entradas poseen nombre, es referenciando estos objetos anteponiendo el signo "$".Por ejemplo, para acceder al 4to slot, con la matriz, podemos escribir `lista3$matriz`, lo cual nos retorna directamente la matriz (no una lista con la matriz).

In [ ]:
# Ejemplo con lista


### **Creación de nuevo slots**

Podemos crear nuevos slots de manera sencilla, indicano el nuevo nombre (utilizando `[]` o `$`) y luego asignando el objeto a almacenar en la nueva entrada.

In [ ]:
# Creamos un slot llamado "nuevo" utilizadno [[]]


In [ ]:
# Creamos un slot llamdo "otro" utilizando $

## **2.2 Dataframes**

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. En este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí. 

 * ¿Cómo se declara un dataframe?<br>
    Mediante la función **data.frame()**, indicando los vectores que conformarán las columnas.
 
 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [ ]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)

df <- data.frame(
  id = 1:3,
  nombre = c("pedro","juan","diego"),
  edad = c(32,33,28)
)

df


In [ ]:
# Acceso a columnas de un data.frame
## Igual que en una lista
df$nombre
df[["nombre"]] #retorna el vector con los nombres, mientras que df["nombres"] retorna un data.frame con los nombres
df[[2]] # ID

In [ ]:
df["nombre"] # Nos entrega un data.frame

In [ ]:
##  Ganamos acceso como matriz
# segunda fila de df
df[2,]

# segunda columna y segunda fila
df[2,2]

# Por nombre de columna
df[2,]$nombre

In [ ]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista


In [ ]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar columnas 1 y 3
# Referenciando el nombre de las columnas


In [ ]:
# Referenciando las posiciones de las columnas




---
# **Taller 2**
La siguiente línea de código permite cargar en memoria, un objeto de extensión *.rds que está almacenado en el disco de la máquina en la ruta actual de trabajo.

Este archivo contiene la información de los contagios por COVID-19 en nuestsro país, según las cifras oficiales entregadas por el ministerio de salud actualizadas al 08 de mayo. En el archivo encontrará, **para cada mes, el total de casos diarios** desglosados según:
   * 'casos_nuevos_con_sintomas': casos nuevos con síntomas del día.
   * 'casos_totales' : casos acumulados a la fecha.
   * 'casos_recuperados': casos recuperados acumulados a la fecha.
   * 'fallecidos': casos fallecidos acumulados.
   * 'casos_activos': casos activos a la fecha.
   * 'casos_nuevos_sin_sintomas': casos asintomáticos del día.
   * 'casos_nuevos_totales': suma de  casos asintomáticos más casos con síntomas del día.
 
 Si bien no será utilizados en este trabajo, también econtrán nuevos registros de acuerdo a los últimos cambios en la metodología de conteo. Para más info pueden referirse al siguiente link:
 https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto5
 
   * 'casos_activos_por_fd'
   * 'casos_activos_por_fis'
   * 'casos_recuperados_por_fis'
   * 'casos_recuperados_por_fd' 
   * 'casos_confirmados_recuperados'
   * 'casos_activos_confirmados'
   * 'casos_probables_acumulados'
   * 'casos_activos_probables'




## Pregunta 1.1

**1a)** ¿Qué clase de objetos es `casos`? <br>
**1b)** ¿Cuántos elementos posee este objeto?<br>
**1c)** ¿Cuáles son los nombres de este objeto?<br>
**1d)** ¿Qué clase de objeto está almacenado en sl _slot_ correspondiente al mes de junio ("jun") y cuántos elementos posee?<br>
**1e)** Para el mes de junio, ¿a qué clase de objeto corresponde `casos_totales` y cuántos elementos posee?




In [ ]:
# P1.1a
## Respuesta 


In [ ]:
# P1.1b
## Respuesta 


In [ ]:
# P1.1c
## Respuesta 


In [ ]:
# P1.1c
## Respuesta 


In [ ]:

# Podemos asumir que dentro de la lista de cada mes existen 15 dataframes asocia
# dos a alguna información específica

In [ ]:
# Para el mes de junio, ¿a qué clase de objeto corresponde casos_totales y cuántos elementos posee?


## Pregunta 1.2

**2a)** ¿Cuántos casos activos existían al 25 de marzo? (indique claramente la expresión de R para obtener el valor solicitado) .<br>
**2b)** Genere cinco nuevas variables llamadas `totales_marzo`,`totales_abril` , `totales_mayo`, `totales_junio` y `totales_julio`, que contengan los dataframes correspondientes al slot `casos_totales` del mes respectivo, (por ejemplo, la variable `totales_julio` debe contener una dataframe de dimensión $8\times2$.<br>
**2c)** Para cada dataframe del paso anterior, genere una nueva columna llamada `mes`, que repita el nombre del mes correspondiente por cada fila.<br>
**2d)** En cada data.frame, agregue una nueva columna llamada `casos_diarios` que contanga la información correspontiende al total de casos nuevos diarios(`casos_nuevos_totales`).


In [ ]:
## Respuesta 

## Pregunta 1.3

**3a)** Con la ayuda de lafunción rbind() , una las filas de las 5 tablas generadas en la pregunta anterior y guarde la tabla resultante en una variable llamada `casos_hist`.<br>
**3b)** En promedio, ¿Cuántos casos hay diariamente desde el 03 de marzo hasta el 08 de julio?<br>
**3c)** En promedio, ¿Cuántos casos hay diariamente **en cada mes** ?.<br>


In [ ]:
# P1.3
## Respuesta


# Sección 2

La siguiente celda de código permitirá cargar en su sesión de trabajo los siguientes vectores:
* `temp_hombre`: Contiene el registro de la temperatura para una muestra de 650 hombres escogidos al azar.
* `temp_mujer`: Contiene el registro de la temperatura para una muestra de 580 mujeres escogidas al azar.


En ambos vectores, **los identificadores (id) de cada persona están contenidos en el atributo `names()`** del vector respectivo.

In [ ]:
temp_h <- readRDS("temp_h.rds")
temp_m <- readRDS("temp_m.rds")

##  Pregunta 2.1

**P1)** A partir de los dos vectores cargados `temp_h` y `temp_m` ustred deberá crear un data.frame llamado **`casos`** con tres columnas y un total de 1230 filas. Las columnas deben ser las siguientes; una con el id del registro, otra con el género y otra con la temperatura registrada. A modo de ejemplo, a continuación se muestra como debería quedar el data.frame:


|id | genero | temperatura|
|---|---|---|
| h_162 | hombre | 36.8 |
| h_140 | hombre | 38.7 |
| h_13  | hombre | 36.1 |
| $\vdots$| $\vdots$ | $\vdots$|
| m_16  | mujer | 39.1 |
| m_502 | mujer | 40.1 |
| m_189 | mujer | 36.8 |

In [ ]:
# P2.1. ---------------------------------------------------------------------
## Respuesta:


## Pregunta 2.2

Adicionalmente, se cuenta con la información de síntomas presentados por cada presona registrada. Esta información se encuentra disponible en el archivo `sintomas.rds`.

**2a)** Cargue el archivo `sintomas.rds` en una variable llamada _sintomas_.<br>
**2b)** ¿Cuál es la clase de este objeto?.<br>
**2c)** Note que cada fila undica con un 1 si la persona presentó el respectivo síntoma y 0 si no. ¿Qué sintomas presentó la persona ubicada en el registro 450?.<br>
**2d)** ¿Qué síntomas y qué temperatura presentó la persona con id "h_537"?. Si es le es de utilidad puede utilizar la función `rownames()`, la cual permite obtener los nombres (id) de las filas de una matriz.<br>

In [ ]:
# P2 .2
## Respuestas:

## Nota de utilidad

Ya sea trabajando con un vector, matriz, data.frame o lista, es posible omitir la selección de alguna(s) de sus posiciones (filas/columnas o slots). Esto se puede llevar a cabo de diversas maneras, por ejemplo:

In [ ]:
# Primero creamos un vector, una matriz, un data.frame  y una lista 

vec <- c(v1 = 1, v2 = 2, v3 = 3,v4 = 4)
mat <- cbind(c(1,1),c(2,2),c(3,3),c(4,4) ) ; rownames(mat) <- c("f1","f2"); colnames(mat) <- c("c1","c2","c3","c4")
dat <- as.data.frame(mat)
lis <- list(s1 = c(1,1), s2 = c(2,2), s3 = c(3,3) , s4 = c(4,4))

### Omisión por posición

In [ ]:
#Si queremos omitir el primer y tercer elmento del vector y la lista
vec[-c(1,3)]
lis[-c(1,3)]

# Misma idea si queremos omitir columnas de una matriz (o data.frame)
mat[,-c(1,3)]
dat[,-c(1,3)]

### Omisión por nombres

In [ ]:
# Por ahora tendremos que ubicar las posiciones de los nombres deseados.

pos_vec <- which(names(vec) %in% c("v1","v3"))
pos_lis <- which(names(lis) %in% c("s1","s3"))
pos_mat <- which(colnames(mat) %in% c("c1","c3"))
pos_dat <- which(names(dat) %in% c("c1","c3"))

vec[-pos_vec]
lis[-pos_lis]

# Misma idea si queremos omitir columnas de una matriz (o data.frame)
mat[,-pos_mat]
dat[,-pos_dat]

Más adelante veremos otras alternivas, como por ejemplo, utilizando funciones del package `dplyr`.

## Pregunta 2.3

Con la ayuda de las funciones `rowSums()` y `colSums()`, identifique lo siguiente.

  **3a)** ¿Cuántos registros presentaron exactamente los 4 síntomas?<br>
  **3b)** ¿Cúantas personas presentaron tos? <br>
  **3c)** ¿Cuál es el síntoma más frecuente?<br>
  

In [ ]:
# P3
##Respuestas:


## Pregunta 2.4

**4a)** La función `as.data.frame()` permite coercionar un objeto de otra clase a `data.frame`.
cree una variable llamada `sintomas_df` con la información  de sintomas pero como data.frame.<br>
**4b)**
Se puede observar que los ids solo están disponibles en los nombres de las filas. Sin embargo esútil tener esta información como una columna más de la tabla. Para ello **cree una nueva columna en la tabla sintomas_df** llamada `id` que contenga los ids de cada registro. 

NOTA: El orden de las filas no ha variado por lo que podemos añadir la columna sin mayores precauciones.<br>
**4c)** ¿Cuántas personas **sólo** presentaron tos y dolor de cabeza?<br>
**4d)** Se sabe que una persona tiene fiebre cuando su temperatura es mayor o igual a los 37.2°. **Cree una nueva columna en la tabla sintomas_df** llamada `tiene_fiebre` que contenga `TRUE` cuando tiene fiebre y `FALSE` en caso contrario. 



In [ ]:
# P4
#Respuestas:
